name: Go

on:
  push:
    branches: [ test ]
    tags:
      - '*'
env:
 GO111MODULE: "on"
 CGO_ENABLED: 0 
 GOOS: "linux" 
 GOARCH: "amd64"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Build
        run: go build -o bin/vault-k8s-secret-engine cmd/main.go

      - name: Test
        run: go test -v ./...
        
      - name: SHA256sum 
        run: sha256sum bin/vault-k8s-secret-engine >> bin/vault-k8s-secret-engine.sha256
            
      - name: Release
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: bin/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
